[tool.black]
line-length = 100
target-version = ["py312"]
exclude = '''
/(
    \.venv|
    \.mypy_cache|
    \.pytest_cache|
    __pycache__|
    build|
    dist
)/
'''
[tool.mypy]
ignore_missing_imports = true

